In [1]:
# numpy means numerical python

In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5]

In [4]:
np.array(l)

array([1, 2, 3, 4, 5])

In [5]:
arr = np.array(l)

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
np.array([[1,2,3],[2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
arr1 = np.array([[1,2,3],[2,3,4]])

In [11]:
arr.ndim

1

In [ ]:
# ndim for dimension

In [12]:
arr1.ndim

2

In [16]:
mat = np.matrix(l)

In [ ]:
# matrix is always 2 dimension at any point of time.

In [14]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [17]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
a = arr

In [20]:
a

array([1, 2, 3, 4, 5])

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
arr[0] = 100

In [23]:
arr

array([100,   2,   3,   4,   5])

In [24]:
a

array([100,   2,   3,   4,   5])

In [ ]:
# this type of data copy operation is called as swollow copy operation

In [25]:
b = np.copy(arr)

In [26]:
b

array([100,   2,   3,   4,   5])

In [27]:
b[0]

100

In [28]:
b[0] = 234

In [29]:
b

array([234,   2,   3,   4,   5])

In [30]:
arr

array([100,   2,   3,   4,   5])

In [ ]:
# this is called as deep copy

In [31]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [35]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [36]:
iterable = (i*i for i in range(5))

In [37]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [38]:
np.fromstring('23 45 56',sep = ' ')

array([23., 45., 56.])

In [39]:
np.fromstring('23 45 56',sep = ',')

/tmp/ipykernel_142/3785816183.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('23 45 56',sep = ',')


array([23.])

In [40]:
arr

array([100,   2,   3,   4,   5])

In [41]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [42]:
arr.ndim

1

In [43]:
arr1.ndim

2

In [44]:
arr.size

5

In [45]:
arr1.size

6

In [46]:
arr.shape

(5,)

In [47]:
arr1.shape

(2, 3)

In [48]:
arr.dtype

dtype('int64')

In [49]:
arr1.dtype

dtype('int64')

In [50]:
range(5)

range(0, 5)

In [51]:
list(range(5))

[0, 1, 2, 3, 4]

In [52]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# range function will only consider integers.

In [55]:
list(np.arange(.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [ ]:
# arange also tells us range but it also takes fractional data.

In [54]:
np.arange(4,10,2)

array([4, 6, 8])

In [56]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [57]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [ ]:
# in logspace by default base is 10 but we can change the base.

In [58]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
# 3D data set 4*2 matrix.

In [63]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [64]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [66]:
arr = np.ones((3,4))

In [67]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [69]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [70]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [71]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# eye means identity matrixes.

In [72]:
arr1 = np.eye(5)

In [73]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
import pandas as pd

In [75]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [77]:
np.random.rand(2,3)

array([[0.07207542, 0.24311812, 0.36369191],
       [0.38519992, 0.16794957, 0.46834518]])

In [78]:
np.random.randn(2,3)

array([[-0.06680256, -0.02605078, -0.03444161],
       [-0.23387094, -0.85646249, -0.08024331]])

In [ ]:
# in randn mean=0 and SD=1, randn means normally distributed dataset

In [80]:
arr2= np.random.randint(1,5,(3,4))

In [81]:
arr2

array([[2, 4, 1, 3],
       [4, 3, 1, 3],
       [2, 2, 3, 3]])

In [82]:
arr2.size

12

In [83]:
arr2.shape

(3, 4)

In [84]:
arr2.reshape(6,2)

array([[2, 4],
       [1, 3],
       [4, 3],
       [1, 3],
       [2, 2],
       [3, 3]])

In [ ]:
# total number of datasets are not going to change even after reshaping

In [85]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [ ]:
# above is example that dataset cannot be changed

In [87]:
arr2.reshape(4,-1)

array([[2, 4, 1],
       [3, 4, 3],
       [1, 3, 2],
       [2, 3, 3]])

In [89]:
arr2.reshape(2,2,3)

array([[[2, 4, 1],
        [3, 4, 3]],

       [[1, 3, 2],
        [2, 3, 3]]])

In [90]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[2]]],


         [[[4]]],


         [[[1]]]],



        [[[[3]]],


         [[[4]]],


         [[[3]]]]],




       [[[[[1]]],


         [[[3]]],


         [[[2]]]],



        [[[[2]]],


         [[[3]]],


         [[[3]]]]]])

In [91]:
arr1 = np.random.randint(1,10,(5,6))

In [92]:
arr1

array([[9, 3, 8, 9, 9, 4],
       [3, 9, 7, 5, 5, 7],
       [9, 3, 8, 4, 2, 1],
       [4, 3, 6, 9, 7, 7],
       [6, 8, 3, 6, 9, 8]])

In [93]:
arr1 > 9

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [94]:
arr1 > 8

array([[ True, False, False,  True,  True, False],
       [False,  True, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False,  True, False]])

In [95]:
arr1[arr1>8]

array([9, 9, 9, 9, 9, 9, 9])

In [96]:
arr1

array([[9, 3, 8, 9, 9, 4],
       [3, 9, 7, 5, 5, 7],
       [9, 3, 8, 4, 2, 1],
       [4, 3, 6, 9, 7, 7],
       [6, 8, 3, 6, 9, 8]])

In [98]:
arr1[0,[0,1]]

array([9, 3])

In [99]:
arr1[2:4,[2,3]]

array([[8, 4],
       [6, 9]])

In [100]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [101]:
arr1

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [102]:
arr2

array([[2, 2, 1],
       [1, 2, 1],
       [1, 2, 2]])

In [103]:
arr1+arr2

array([[3, 4, 2],
       [2, 4, 2],
       [2, 4, 3]])

In [104]:
arr1-arr2

array([[-1,  0,  0],
       [ 0,  0,  0],
       [ 0,  0, -1]])

In [105]:
arr1*arr2

array([[2, 4, 1],
       [1, 4, 1],
       [1, 4, 2]])

In [ ]:
# not a matrix multiplication but multiplication by index.

In [ ]:
# for matrix multiplication use @

In [106]:
arr1@arr2

array([[5, 8, 5],
       [5, 8, 5],
       [5, 8, 5]])

In [107]:
arr1/arr2

array([[0.5, 1. , 1. ],
       [1. , 1. , 1. ],
       [1. , 1. , 0.5]])

In [108]:
arr1/0

/tmp/ipykernel_142/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
# infinite do exist in numpy

In [ ]:
#Numpy - Broadcasting.

In [110]:
arr = np.zeros((3,4))

In [111]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [112]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
# this is broadcasting. I am broadcasting this 5.

In [113]:
a = np.array([1,2,3,4])

In [114]:
arr+1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [115]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [118]:
b = np.array([[3,4,5]])

In [119]:
arr+b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [122]:
arr1 = arr+b.T

In [121]:
b.T

array([[3],
       [4],
       [5]])

In [123]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [124]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [125]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [126]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [127]:
np.min(arr1)

3.0

In [128]:
np.max(arr1)

5.0

In [ ]:
#Numpy - Array Manipulation.

In [130]:
arr = np.random.randint(1,10,(4,4))

In [131]:
arr

array([[8, 7, 6, 8],
       [8, 7, 2, 6],
       [6, 9, 1, 8],
       [3, 1, 6, 8]])

In [132]:
arr.reshape(8,2)

array([[8, 7],
       [6, 8],
       [8, 7],
       [2, 6],
       [6, 9],
       [1, 8],
       [3, 1],
       [6, 8]])

In [133]:
arr.reshape(2,8)

array([[8, 7, 6, 8, 8, 7, 2, 6],
       [6, 9, 1, 8, 3, 1, 6, 8]])

In [134]:
arr

array([[8, 7, 6, 8],
       [8, 7, 2, 6],
       [6, 9, 1, 8],
       [3, 1, 6, 8]])

In [135]:
arr.T

array([[8, 8, 6, 3],
       [7, 7, 9, 1],
       [6, 2, 1, 6],
       [8, 6, 8, 8]])

In [136]:
arr.flatten()

array([8, 7, 6, 8, 8, 7, 2, 6, 6, 9, 1, 8, 3, 1, 6, 8])

In [137]:
arr

array([[8, 7, 6, 8],
       [8, 7, 2, 6],
       [6, 9, 1, 8],
       [3, 1, 6, 8]])

In [138]:
np.expand_dims(arr,axis=1)

array([[[8, 7, 6, 8]],

       [[8, 7, 2, 6]],

       [[6, 9, 1, 8]],

       [[3, 1, 6, 8]]])

In [139]:
np.expand_dims(arr,axis=0)

array([[[8, 7, 6, 8],
        [8, 7, 2, 6],
        [6, 9, 1, 8],
        [3, 1, 6, 8]]])

In [140]:
data = np.array([[1],[2],[3]])

In [141]:
np.squeeze(data)

array([1, 2, 3])

In [142]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [143]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [144]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [145]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#Numpy - Binary Operators.

In [146]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [147]:
arr1

array([[1, 7, 4, 7],
       [8, 1, 3, 4],
       [4, 1, 6, 8]])

In [148]:
arr2

array([[9, 3, 7, 6],
       [8, 5, 6, 3],
       [4, 4, 6, 1]])

In [149]:
arr1+arr2

array([[10, 10, 11, 13],
       [16,  6,  9,  7],
       [ 8,  5, 12,  9]])

In [150]:
arr1*arr2

array([[ 9, 21, 28, 42],
       [64,  5, 18, 12],
       [16,  4, 36,  8]])

In [151]:
arr1/arr2

array([[0.11111111, 2.33333333, 0.57142857, 1.16666667],
       [1.        , 0.2       , 0.5       , 1.33333333],
       [1.        , 0.25      , 1.        , 8.        ]])

In [152]:
arr1-arr2

array([[-8,  4, -3,  1],
       [ 0, -4, -3,  1],
       [ 0, -3,  0,  7]])

In [153]:
arr1**arr2

array([[       1,      343,    16384,   117649],
       [16777216,        1,      729,       64],
       [     256,        1,    46656,        8]])

In [154]:
~arr1

array([[-2, -8, -5, -8],
       [-9, -2, -4, -5],
       [-5, -2, -7, -9]])

In [ ]:
# ~arr1 means negation of arr1

In [155]:
arr1>arr2

array([[False,  True, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]])

In [156]:
arr1<arr2

array([[ True, False,  True, False],
       [False,  True,  True, False],
       [False,  True, False, False]])

In [ ]:
#Numpy - String Functions.

In [157]:
arr = np.array(["aayush","srivastava"])

In [158]:
arr

array(['aayush', 'srivastava'], dtype='<U10')

In [159]:
np.char.upper(arr)

array(['AAYUSH', 'SRIVASTAVA'], dtype='<U10')

In [160]:
np.char.capitalize(arr)

array(['Aayush', 'Srivastava'], dtype='<U10')

In [161]:
np.char.title(arr)

array(['Aayush', 'Srivastava'], dtype='<U10')

In [162]:
arr1

array([[1, 7, 4, 7],
       [8, 1, 3, 4],
       [4, 1, 6, 8]])

In [163]:
np.sin(arr1)

array([[ 0.84147098,  0.6569866 , -0.7568025 ,  0.6569866 ],
       [ 0.98935825,  0.84147098,  0.14112001, -0.7568025 ],
       [-0.7568025 ,  0.84147098, -0.2794155 ,  0.98935825]])

In [164]:
np.cos(arr1)

array([[ 0.54030231,  0.75390225, -0.65364362,  0.75390225],
       [-0.14550003,  0.54030231, -0.9899925 , -0.65364362],
       [-0.65364362,  0.54030231,  0.96017029, -0.14550003]])

In [165]:
np.tan(arr1)

array([[ 1.55740772,  0.87144798,  1.15782128,  0.87144798],
       [-6.79971146,  1.55740772, -0.14254654,  1.15782128],
       [ 1.15782128,  1.55740772, -0.29100619, -6.79971146]])

In [166]:
np.log10(arr1)

array([[0.        , 0.84509804, 0.60205999, 0.84509804],
       [0.90308999, 0.        , 0.47712125, 0.60205999],
       [0.60205999, 0.        , 0.77815125, 0.90308999]])

In [167]:
np.exp(arr1)

array([[2.71828183e+00, 1.09663316e+03, 5.45981500e+01, 1.09663316e+03],
       [2.98095799e+03, 2.71828183e+00, 2.00855369e+01, 5.45981500e+01],
       [5.45981500e+01, 2.71828183e+00, 4.03428793e+02, 2.98095799e+03]])

In [169]:
np.power(arr1,2)

array([[ 1, 49, 16, 49],
       [64,  1,  9, 16],
       [16,  1, 36, 64]])

In [170]:
np.mean(arr1)

4.5

In [172]:
np.median(arr1)

4.0

In [174]:
np.std(arr1)

2.565800719723442

In [175]:
np.var(arr1)

6.583333333333333

In [176]:
np.min(arr1)

1

In [177]:
np.max(arr1)

8

In [ ]:
#Numpy - Arithmetic Operations.

In [178]:
arr1

array([[1, 7, 4, 7],
       [8, 1, 3, 4],
       [4, 1, 6, 8]])

In [179]:
arr2

array([[9, 3, 7, 6],
       [8, 5, 6, 3],
       [4, 4, 6, 1]])

In [180]:
arr1-arr2

array([[-8,  4, -3,  1],
       [ 0, -4, -3,  1],
       [ 0, -3,  0,  7]])

In [181]:
np.subtract(arr1,arr2)

array([[-8,  4, -3,  1],
       [ 0, -4, -3,  1],
       [ 0, -3,  0,  7]])

In [182]:
np.multiply(arr1,arr2)

array([[ 9, 21, 28, 42],
       [64,  5, 18, 12],
       [16,  4, 36,  8]])

In [183]:
np.mod(arr1,arr2)

array([[1, 1, 4, 1],
       [0, 1, 3, 1],
       [0, 1, 0, 0]])

In [184]:
np.power(arr1,arr2)

array([[       1,      343,    16384,   117649],
       [16777216,        1,      729,       64],
       [     256,        1,    46656,        8]])

In [185]:
np.sqrt(arr1)

array([[1.        , 2.64575131, 2.        , 2.64575131],
       [2.82842712, 1.        , 1.73205081, 2.        ],
       [2.        , 1.        , 2.44948974, 2.82842712]])

In [186]:
np.sqrt(arr2)

array([[3.        , 1.73205081, 2.64575131, 2.44948974],
       [2.82842712, 2.23606798, 2.44948974, 1.73205081],
       [2.        , 2.        , 2.44948974, 1.        ]])

In [ ]:
#Numpy - Statistical Function

In [187]:
arr1

array([[1, 7, 4, 7],
       [8, 1, 3, 4],
       [4, 1, 6, 8]])

In [188]:
np.mean(arr1)

4.5

In [189]:
np.std(arr1)

2.565800719723442

In [190]:
np.median(arr1)

4.0

In [ ]:
#sort, search and counting functions.

In [195]:
arr = np.array([4,2,8,5,3,9,12,56])

In [196]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [197]:
arr.sort()

In [198]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [ ]:
# how to perform a search sort operation.

In [199]:
np.searchsorted(arr,6)

4

In [200]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [201]:
np.count_nonzero(arr1)

6

In [202]:
np.where(arr1 >0)

(array([1, 2, 3, 4, 5, 9]),)

In [206]:
np.extract(arr1>2,arr1)

array([324, 645,  65,   6,   6, 234])

In [ ]:
#Numpy - Byte swapping

In [207]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [210]:
arr.byteswap(True)

array([ 144115188075855872,  216172782113783808,  288230376151711744,
        360287970189639680,  576460752303423488,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [211]:
arr

array([ 144115188075855872,  216172782113783808,  288230376151711744,
        360287970189639680,  576460752303423488,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [ ]:
#Numpy - Copies and Views.

In [212]:
arr

array([ 144115188075855872,  216172782113783808,  288230376151711744,
        360287970189639680,  576460752303423488,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [213]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [214]:
a = np.copy(arr1)

In [215]:
b = arr1.view()

In [216]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [217]:
b[0]=234

In [218]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [219]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
# view is trying to create a swallow copy

In [ ]:
# copy is an example of deep copy

In [ ]:
#Numpy - Matrix Library.

In [220]:
import numpy.matlib as nm

In [221]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [223]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# matrix is an subclass of subset of an array inside numpy.

In [224]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
#Numpy - Linear Algebra

In [225]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [226]:
arr1 = np.random.randint([[2,3],[4,5]])

In [227]:
arr2 = np.random.randint([[5,3],[2,5]])

In [228]:
arr1

array([[1, 1],
       [3, 2]])

In [229]:
arr2

array([[2, 0],
       [0, 1]])

In [ ]:
# for dot product of arr1 and arr2

In [230]:
np.dot(arr1,arr2)

array([[2, 1],
       [6, 2]])

In [231]:
arr1@arr2

array([[2, 1],
       [6, 2]])